### ISSUE TITLE
Clarification: correct_edge_choices is array of all zeros, while valid_edge_choices has a few candidates

### ISSUE THREAD

**Issue by HiokHian** [microsoft/molecule-generation#42]
Hi,

After running the preprocessing script and looking into some of the individual generation trace steps, I found that some of the steps have valid_edge_choices as a non empty array of possible edges but the corresponding correct_edge_choices for the same step is an array of all zeros. Could I clarify what does this mean in this context? Does that mean in this case that during this step we shouldn't be adding an edge to the molecular graph and should instead be adding an atom/motif? Thanks!

**Comment by kmaziarz** [comment]
Hi - I don't know the answer off the top of my head; let me take a closer look and get back to you 🙂

**Comment by kmaziarz** [comment]
@HiokHian I refreshed my memory; you are indeed correct: steps where all of `correct_edge_choices` are zeros are when we should not add any edges. This usually means we should add some atom/motif (thus `correct_node_type_choices` would be a non-empty list), but it could also be that we should end the generation altogether (and then `correct_node_type_choices` would be an empty list). Note that whether we should be making the next node choice at all is encoded as `correct_node_type_choices` being `None` or not; if it's the end of the generation, then we _should_ make that choice and say "no more nodes", so in that case `correct_node_type_choices` will not be `None` and rather an empty list.

One source of confusion here is that in the paper we describe two distinct steps, one when we decide no more edges will be added, and another when we select an atom/motif; in the code these two are merged in a single step. This is mostly for efficiency: after deciding that no more edges will be added from the current focus node, the graph doesn't change, and thus the GNN embeddings can be directly reused to choose an atom/motif.

To explore what *kinds* of steps exist in the data, you can for example run the following script
```python
from collections import Counter
from dpu_utils.utils import RichPath

path = "data/traces/train_0/train_0.pkl.gz"

# Extract the info about valid edge choices and node types.
traces = [
    list(zip(trace.valid_edge_choices, trace.correct_edge_choices, trace.correct_node_type_choices))
    for trace in RichPath.create(path).read_by_file_suffix()
]

# Concatenate the steps from all the traces.
traces = sum(traces, [])

counter = Counter()

# Aggregate all *kinds* of steps that occur in the data.
for valid_edges, correct_edges, correct_node_types in traces:
    no_edge_choices = len(valid_edges) == 0
    all_edge_choices_incorrect = correct_edges.sum() < 1e-5
    some_correct_node_types = correct_node_types is not None

    counter[(no_edge_choices, all_edge_choices_incorrect, some_correct_node_types)] += 1

print(counter)
```
Ran on 200 molecules from the Guacamol training set, this gives
```python
Counter({(False, False, False): 2944, (False, True, True): 2020, (True, True, True): 929, (True, True, False): 276})
```

As you can see, there are only four "kinds" of steps:
- `(False, False, False)`: some valid edges could be added, and one (or more) are correct; we're not choosing a node type at this time
- `(False, True, True)`: some valid edges could be added, but we should not add any, and instead choose a node type
- `(True, True, True)`: as above, but there are no valid edges that could be added (e.g. we ran out of valence, or this is the first atom/motif), thus it's obvious we should add a node
- `(True, True, False)`: this step is special: no valid edges or node types, because we're now choosing an attachment point in a motif; you'll find that these are exactly the steps where `correct_attachment_point_choices` is not `None`

Let me know if you have any more questions and I'd be happy to clarify further; the trace generation is a bit convoluted in a few places 🙂

**Comment by HiokHian** [comment]
Thank you very much for the detailed explanation! That clears it up.
