### ISSUE TITLE
Computing likely next actions

### ISSUE THREAD

**Issue by orangese** [microsoft/molecule-generation#63]
Hi! I'm trying to compute the top `k` most likely next actions given a partially generated molecule. Each "next action" consists of first selecting an atom/motif via `PickAtomOrMotif`, then picking an attachment and bond via `PickAttachment` and `PickBond` (assuming `END_GEN` isn't sampled). The most likely actions can be determined by the conditional probability of observing each selection (atom/motif, then attachment, then bond) given the initial scaffold. How would I go about doing this with the current API?

Thanks for your help!

**Comment by kmaziarz** [comment]
You could do something like the below to get a sequence of decoding steps:
```python
from molecule_generation import load_model_from_directory
from molecule_generation.utils.moler_decoding_utils import *


with load_model_from_directory("./chkpt_repo") as model:
    [embedding] = model.encode(["O=CNc1ccccc1"])
    [(smiles, steps)] = model.decode([embedding], include_generation_steps=True)

    print(f"Decoded SMILES: {smiles}\n")

    for idx, step in enumerate(steps):
        print(f"Step {idx}")

        if isinstance(step, MoleculeGenerationAtomChoiceInfo):
            print(f"Atom choice step with options:")
            for idx, prob in enumerate(step.type_idx_to_prob):
                if prob > 0.02:
                    print(f">> node type idx {idx}; prob {prob}")
        elif isinstance(step, MoleculeGenerationEdgeChoiceInfo):
            print(f"Edge choice step with options:")
            for option in step.candidate_edge_infos:
                print(f">> to node {option.target_node_idx}; logprob {option.logprob}")
        elif isinstance(step, MoleculeGenerationAttachmentPointChoiceInfo):
            print(f"Attachment point choice step with probs {step.candidate_idx_to_prob}")
        else:
            assert False

        print("")
```

Using the checkpoint from `README.md`, this prints
```
Decoded SMILES: O=CNC1=CC=CC=C1

Step 0
Atom choice step with options:
>> node type idx 37; prob 0.44812485575675964
>> node type idx 39; prob 0.5475685596466064

Step 1
Atom choice step with options:
>> node type idx 37; prob 0.9999274015426636

Step 2
Attachment point choice step with probs [1.]

Step 3
Edge choice step with options:
>> to node 0; logprob -0.5086194276809692
>> to node 1; logprob -0.9196093082427979

Step 4
Atom choice step with options:
>> node type idx 37; prob 0.2261890470981598
>> node type idx 165; prob 0.7720987200737
```

We can see that in the first step the model considered atom/motif type IDs `37` and `39`, with the latter being slightly preferred. Knowing what molecule we ended up with, it's easy to guess what these IDs correspond to, but unfortunately I think the mapping is not easily available in the high-level interface. We can use one of the lower-level functions to get it:

```python
from molecule_generation.utils.model_utils import load_vae_model_and_dataset

dataset, _ = load_vae_model_and_dataset("./chkpt_repo/GNN_Edge_MLP_MoLeR__2022-02-24_07-16-23_best.pkl")

for type_id in [37, 39]:
    print(f"Node type ID {type_id} = {dataset._node_type_index_to_string[type_id + 1]}")
```

which (unsurprisingly) gives us:
```
Node type ID 37 = C1=CC=CC=C1
Node type ID 39 = NC=O
```

Note the `+1` in the code above; this is due to the fact that the first node type is technically an `UNK` which is later stripped away, hence the shift.

Coming back to our sequence of steps, we know that the model added `39` (`NC=O`) in the first step, and indeed in the second step it chooses to add the other motif (`37` i.e. `c1ccccc1`). It then chooses an attachment point (due to symmetry there is only one choice, so nothing to do here), adds a bond between the motifs, and finally chooses `END_GEN`. The bond/attachment steps contain atom IDs, which one would have to map back looking at the underlying `rdkit` molecules, but it hopefully shouldn't be too hard to do that.

In a scaffold-based scenario `decode` would need the scaffold as an argument, and then the sequence of steps would start from the scaffold instead of starting from scratch. Other than that things should work in the same way.

Finally, you can also take a look at our visualization CLI and the code that underlies it. It has to do essentially the same analysis to understand and plot the steps taken during decoding. However, note that this code uses the lower-level utils instead of the higher-level wrapper, partially due to the fact that it predates the latter.

Hope this helps, and let me know if you have any further questions.

**Comment by orangese** [comment]
Thanks for your detailed explanation, that's really helpful. Is there any way to probe the decoder to allow for selection of an atom/motif/bond/etc. that doesn't necessarily have the highest probability? In your code above, I'm wondering if it's possible, for example, to see how `Steps 1-4` would have played out should the model have selected `node type idx 37` instead of `node type idx 39` in `Step 0`. I'm assuming that this would require a more step-by-step decoding process, is there support for that?

Thanks again for the help!

**Comment by kmaziarz** [comment]
> Is there any way to probe the decoder to allow for selection of an atom/motif/bond/etc. that doesn't necessarily have the highest probability?

You'd need to play around with some internals to achieve this; what to change exactly would depend on what level of control you'd like to have. If you just want to obtain several likely sequences of actions, then you can pass a `beam_size` argument to the model wrapper, which will tell the decoder to explore a beam of sequences of a certain size. However, it would still return the most likely beam, but it's easy to extract what the beams were: if you look at `_decode_from_latents` in `moler_inference_server.py`, at some point it does
```python
best_decoder_state = max(per_sampled_latent_results[1], key=lambda s: s.logprob)
```
which is when we limit ourselves to only the best beam; you could simply print out the sequences of steps in the other beams if that's what you want. However, note that the different beams are not guaranteed to give different final molecules, as there may be many ways to build up the same molecule.

If you want more control over which sequences of steps are explored then you might need to hack the `decode` function itself in `moler_decoder.py`.
